apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sentinel-ingestion.fullname" . }}
  labels: {{ include "sentinel-ingestion.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels: {{ include "sentinel-ingestion.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{ include "sentinel-ingestion.selectorLabels" . | nindent 8 }}
      annotations: { sidecar.istio.io/inject: "true" }
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      securityContext: {{ toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: ingestion
          securityContext: {{ toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports: [{ containerPort: {{ .Values.service.targetPort }} }]
          envFrom: [{ configMapRef: { name: {{ include "sentinel-ingestion.fullname" . }}-env } }]
          resources: {{ toYaml .Values.resources | nindent 12 }}
